import { createSlice} from "@reduxjs/toolkit";
import {select} from "@redux-saga/core/effects";

export const MovieSlice = createSlice({
    name: "MovieSlice",

    initialState:{
        movies: [
            {
                countries:{country: 'Россия'},
                filmId:4370148,
                filmLength:"01:53",
                genres:[
                    {genre: 'комедия'},
                    {genre: 'семейный'},
                ],
                nameEn:null,
                nameRu:"Чебурашка",
                posterUrl:"https://kinopoiskapiunofficial.tech/images/posters/kp/4370148.jpg",
                posterUrlPreview:"https://kinopoiskapiunofficial.tech/images/posters/kp_small/4370148.jpg",
                rating:"8.0",
                ratingChange:null,
                ratingVoteCount:22901,
                year:"2022",
            },
            {

                countries:[{country: 'США'}],
                filmId:505898,
                filmLength:"03:12",
                genres:[

                    {genre: 'фантастика'},
                    {genre: 'приключения'},
                    {genre: 'боевик'},
                    {genre: 'фэнтези'},
                ],
                nameEn:"Avatar: The Way of Water",
                nameRu:"Аватар: Путь воды",
                posterUrl:"https://kinopoiskapiunofficial.tech/images/posters/kp/505898.jpg",
                posterUrlPreview:"https://kinopoiskapiunofficial.tech/images/posters/kp_small/505898.jpg",
                rating:"7.9",
                ratingChange:null,
                ratingVoteCount:15533,
                year:"2022",
            },
            {

                countries:[

                    {country: 'США'},
                    {country: 'Япония'},
                ],
                filmId:840821,
                filmLength:"01:42",
                genres:[

                    {genre: 'приключения'},
                    {genre: 'фэнтези'},
                    {genre: 'комедия'},
                    {genre: 'мультфильм'},
                ],
                nameEn:"Puss in Boots: The Last Wish",
                nameRu:"Кот в сапогах 2: Последнее желание",
                posterUrl:"https://kinopoiskapiunofficial.tech/images/posters/kp/840821.jpg",
                posterUrlPreview:"https://kinopoiskapiunofficial.tech/images/posters/kp_small/840821.jpg",
                rating:"8.1",
                ratingChange:null,
                ratingVoteCount:15601,
                year:"2022",
            },
            {

                countries:[{country: 'США'}],
                filmId:1405508,
                filmLength:"01:54",
                genres:[
                    {genre: 'триллер'},
                    {genre: 'боевик'},
                    {genre: 'комедия'},
                ],
                nameEn:"Operation Fortune: Ruse de guerre",
                nameRu:"Операция «Фортуна»: Искусство побеждать",
                posterUrl:"https://kinopoiskapiunofficial.tech/images/posters/kp/1405508.jpg",
                posterUrlPreview:"https://kinopoiskapiunofficial.tech/images/posters/kp_small/1405508.jpg",
                rating:"99.0%",
                ratingChange:null,
                ratingVoteCount:6,
                year:"2023",
            },
            {
                countries: [
                    {country: 'США'},
                    {country: 'Великобритания'},
                    {country: 'Ирландия'},
                ],
                filmId:1354524,
                filmLength:"01:54",
                genres:[
                    {genre: 'драма'},
                    {genre: 'комедия'}
                ],
                nameEn:"The Banshees of Inisherin",
                nameRu:"Банши Инишерина",
                posterUrl:"https://kinopoiskapiunofficial.tech/images/posters/kp/1354524.jpg",
                posterUrlPreview:"https://kinopoiskapiunofficial.tech/images/posters/kp_small/1354524.jpg",
                rating:"7.7",
                ratingChange:null,
                ratingVoteCount:11051,
                year:"2022",

            },
            {
                countries:[
                    {country: 'США'},
                    {country: 'Швейцария'},
                    {country: 'Франция'},
                    {country: 'Великобритания'},
                    {country: 'Швеция'},
                    {country: 'Германия'},
                    {country: 'Мексика'},
                    {country: 'Дания'},
                    {country: 'Турция'},
                    {country: 'Греция'},

                ],
                filmId:1348487,
                filmLength:"02:27",
                genres:[
                    {genre: 'драма'},
                    {genre: 'комедия'},
                ],
                nameEn:"Triangle of Sadness",
                nameRu:"Треугольник печали",
                posterUrl:"https://kinopoiskapiunofficial.tech/images/posters/kp/1348487.jpg",
                posterUrlPreview:"https://kinopoiskapiunofficial.tech/images/posters/kp_small/1348487.jpg",
                rating:"7.3",
                ratingChange:null,
                ratingVoteCount:18298,
                year:"2022",

            },
            {
                countries:[
                    {country: 'США'},
                ],
                filmId:1322324,
                filmLength:"02:19",
                genres:[
                    {genre: 'драма'},
                    {genre: 'фантастик'},
                    {genre: 'приключения'},
                    {genre: 'боевик'},
                    {genre: 'комедия'},
                ],

                nameEn:"Everything Everywhere All at Once",
                nameRu:"Всё везде и сразу",
                posterUrl:"https://kinopoiskapiunofficial.tech/images/posters/kp/1322324.jpg",
                posterUrlPreview:"https://kinopoiskapiunofficial.tech/images/posters/kp_small/1322324.jpg",
                rating:"7.3",
                ratingChange:null,
                ratingVoteCount:277123,
                year:"2021",
            },
            {
                countries:[
                    {country: 'США'},
                    {country: 'Индия'}
                ],


                filmId:4472502,
                filmLength:"02:31",
                genres:[
                    {genre: 'драма'},
                ],

                nameEn:"The Fabelmans",
                nameRu:"Фабельманы",
                posterUrl:"https://kinopoiskapiunofficial.tech/images/posters/kp/4472502.jpg",
                posterUrlPreview:"https://kinopoiskapiunofficial.tech/images/posters/kp_small/4472502.jpg",
                rating:"7.7",
                ratingChange:null,
                ratingVoteCount:8177,
                year:"2022",

            },
            {
                countries:[
                    {country: 'США'},
                ],

                filmId:251733,
                filmLength:"02:42",
                genres:[
                    {genre: 'драма'},
                    {genre: 'фантастика'},
                    {genre: 'приключения'},
                    {genre: 'боевик'},
                ],


                nameEn:"Avatar",
                nameRu:"Аватар",
                posterUrl:"https://kinopoiskapiunofficial.tech/images/posters/kp/251733.jpg",
                posterUrlPreview:"https://kinopoiskapiunofficial.tech/images/posters/kp_small/251733.jpg",
                rating:"8.0",
                ratingChange:null,
                ratingVoteCount:918231,
                year:"2009",
            },
            {
                countries:[
                    {country: 'США'},
                    {country: 'Великобритания'},
                    {country: 'Германия'},
                ],


                filmId:316376,
                filmLength:"02:28",
                genres:[
                    {genre: 'драма'},
                    {genre: 'боевик'},
                    {genre: 'военный'},
                    {genre: 'история'},
                ],


                nameEn:"Im Westen nichts Neues",
                nameRu:"На Западном фронте без перемен",
                posterUrl:"https://kinopoiskapiunofficial.tech/images/posters/kp/316376.jpg",
                posterUrlPreview:"https://kinopoiskapiunofficial.tech/images/posters/kp_small/316376.jpg",
                rating:"7.7",
                ratingChange:null,
                ratingVoteCount:23890,
                year:"2022",
            },
            {
                countries:[
                    {country: 'США'},
                ],
                filmId:1257264,
                filmLength:"01:47",
                genres:[
                    {genre: 'триллер'},
                    {genre: 'комедия'},
                ],
                nameEn:"The Menu",
                nameRu:"Меню",
                posterUrl:"https://kinopoiskapiunofficial.tech/images/posters/kp/1257264.jpg",
                posterUrlPreview:"https://kinopoiskapiunofficial.tech/images/posters/kp_small/1257264.jpg",
                rating:"6.9",
                ratingChange:null,
                ratingVoteCount:5038,
                year:"2022",

            },
            {
                countries:[
                    {country: 'США'},
                    {country: 'Великобритания'},
                ],
                filmId:1338502,
                filmLength:"01:47",
                genres:[
                    {genre: 'триллер'},
                    {genre: 'боевик'},
                ],
                nameEn:"Plane",
                nameRu:"Крушение",
                posterUrl:"https://kinopoiskapiunofficial.tech/images/posters/kp/1338502.jpg",
                posterUrlPreview:"https://kinopoiskapiunofficial.tech/images/posters/kp_small/1338502.jpg",
                rating:"99.0%",
                ratingChange:null,
                ratingVoteCount:197,
                year:"2023",
            },
            {
                countries:[
                    {country: 'США'}
                ],
                filmId:1343908,
                filmLength:"02:20",
                genres:[
                    {genre: 'криминал'},
                    {genre: 'детектив'}
                ],
                nameEn:"Glass Onion: A Knives Out Mystery",
                nameRu:"Достать ножи: Стеклянная луковица",
                posterUrl:"https://kinopoiskapiunofficial.tech/images/posters/kp/1343908.jpg",
                posterUrlPreview:"https://kinopoiskapiunofficial.tech/images/posters/kp_small/1343908.jpg",
                rating:"99.0%",
                ratingChange:null,
                ratingVoteCount:937,
                year:"2022",
            },
            {
                countries:[
                    {country: 'США'}
                ],
                filmId:4511218,
                filmLength:"02:38",
                genres:[
                    {genre: 'драма'},
                    {genre: 'музыка'},
                ],
                nameEn:"Tár",
                nameR:"Тар",
                posterUrl:"https://kinopoiskapiunofficial.tech/images/posters/kp/4511218.jpg",
                posterUrlPreview:"https://kinopoiskapiunofficial.tech/images/posters/kp_small/4511218.jpg",
                rating:"7.4",
                ratingChange:null,
                ratingVoteCount:2642,
                year:"2022",
            },
            {
                countries:[
                    {country: 'США'},
                    {country: 'Великобритания'},
                    {country: 'Германия'},
                ],
                filmId:1450722,
                filmLength:"01:33",
                genres:[
                    {genre: 'приключения'},
                    {genre: 'комедия'},
                    {genre: 'мультфильм'},
                    {genre: 'семейный'},
                ],
                nameEn:"The Amazing Maurice",
                nameRu:"Изумительный Морис",
                posterUrl:"https://kinopoiskapiunofficial.tech/images/posters/kp/1450722.jpg",
                posterUrlPreview:"https://kinopoiskapiunofficial.tech/images/posters/kp_small/1450722.jpg",
                rating:"6.5",
                ratingChange:null,
                ratingVoteCount:297,
                year:"2022"
            },
            {
                countries:[
                    {country: 'США'},
                    {country: 'Чехия'},
                    {country: 'Финляндия'},
                ],
                filmId:1238170,
                filmLength:"01:51",
                genres:[
                    {genre: 'триллер'},
                    {genre: 'ужасы'}
                ],
                nameEn:"The Devil Conspiracy",
                nameRu:"Заговор дьявола",
                posterUrl:"https://kinopoiskapiunofficial.tech/images/posters/kp/1238170.jpg",
                posterUrlPreview:"https://kinopoiskapiunofficial.tech/images/posters/kp_small/1238170.jpg",
                rating:null,
                ratingChange:null,
                ratingVoteCount:123,
                year:"2022",
            },
            {
                countries:[
                    {country: 'США'},
                ],
                filmId:4308297,
                filmLength:"01:44",
                genres:[
                    {genre: 'драма'},
                ],
                nameEn:"Women Talking",
                nameRu:"Говорят женщины",
                posterUrl:"https://kinopoiskapiunofficial.tech/images/posters/kp/4308297.jpg",
                posterUrlPreview:"https://kinopoiskapiunofficial.tech/images/posters/kp_small/4308297.jpg",
                rating:"99.0%",
                ratingChange:null,
                ratingVoteCount:23,
                year:"2022",
            },
            {
                countries:[
                    {country: 'Россия'}
                ],
                filmId:5078983,
                filmLength:"01:49",
                genres:[
                    {genre: 'приключения'},
                    {genre: 'комедия'},
                ],
                nameEn:null,
                nameRu:"Мажор в Сочи",
                posterUrl:"https://kinopoiskapiunofficial.tech/images/posters/kp/5078983.jpg",
                posterUrlPreview:"https://kinopoiskapiunofficial.tech/images/posters/kp_small/5078983.jpg",
                rating:"7.1",
                ratingChange:null,
                ratingVoteCount:436771,
                year:"2022",
            },
            {
                countries:[
                    {country: 'США'},
                ],
                filmId:1283955,
                filmLength:"03:09",
                genres:[
                    {genre: 'драма'},
                    {genre: 'комедия'},
                    {genre: 'история'},
                ],
                nameEn:"Babylon",
                nameRu:"Вавилон",
                posterUrl:"https://kinopoiskapiunofficial.tech/images/posters/kp/1283955.jpg",
                posterUrlPreview:"https://kinopoiskapiunofficial.tech/images/posters/kp_small/1283955.jpg",
                rating:"99.0%",
                ratingChange:null,
                ratingVoteCount:875,
                year:"2022",
            },
            {
                countries:[
                    {country: 'США'},
                    {country: 'Великобритания'},
                ],
                filmId:1143242,
                filmLength:"01:53",
                genres:[
                    {genre: 'криминал'},
                    {genre: 'боевик'},
                    {genre: 'комедия'},
                ],
                nameEn:"The Gentlemen",
                nameRu:"Джентльмены",
                posterUrl:"https://kinopoiskapiunofficial.tech/images/posters/kp/1143242.jpg",
                posterUrlPreview:"https://kinopoiskapiunofficial.tech/images/posters/kp_small/1143242.jpg",
                rating:"8.5",
                ratingChange:null,
                ratingVoteCount:1231889,
                year:"2019",
            },
            {
                countries:[
                    {country: 'США'}
                ],
                filmId:572032,
                filmLength:"02:10",
                genres:[
                    {genre: 'драма'},
                    {genre: 'боевик'},
                ],
                nameEn:"Top Gun: Maverick",
                nameRu:"Топ Ган: Мэверик",
                posterUrl:"https://kinopoiskapiunofficial.tech/images/posters/kp/572032.jpg",
                posterUrlPreview:"https://kinopoiskapiunofficial.tech/images/posters/kp_small/572032.jpg",
                rating:"7.8",
                ratingChange:null,
                ratingVoteCount:73012,
                year:"2022",
            },
            {
                countries:[
                    {country: 'США'},
                ],
                filmId:1188529,
                filmLength:"02:10",
                genres: [
                    {genre: 'драма'},
                    {genre: 'криминал'},
                    {genre: 'детектив'},
                    {genre: 'комедия'},
                ],
                nameEn:"Knives Out",
                nameRu:"Достать ножи",
                posterUrl:"https://kinopoiskapiunofficial.tech/images/posters/kp/1188529.jpg",
                posterUrlPreview:"https://kinopoiskapiunofficial.tech/images/posters/kp_small/1188529.jpg",
                rating:"8.1",
                ratingChange:null,
                ratingVoteCount:792357,
                year:"2019"
            },
            {
                countries:[
                    {country: 'Россия'}

                ],
                filmId:4771048,
                filmLength:"01:20",
                genres:[
                    {genre: 'криминал'},
                    {genre: 'детектив'},
                    {genre: 'боевик'},
                    {genre: 'комедия'}
                ],
                nameEn:null,
                nameRu:"Гром: Трудное детство",
                posterUrl:"https://kinopoiskapiunofficial.tech/images/posters/kp/4771048.jpg",
                posterUrlPreview:"https://kinopoiskapiunofficial.tech/images/posters/kp_small/4771048.jpg",
                rating:"97.0%",
                ratingChange:null,
                ratingVoteCount:0,
                year:"2022",
            },
            {
                countries:[
                    {country: 'США'},
                ],
                filmId:1199773,
                filmLength:"02:41",
                genres:[
                    {genre: 'драма'},
                    {genre: 'фантастика'},
                    {genre: 'боевик'}
                ],
                nameEn:"Black Panther: Wakanda Forever",
                nameRu:"Чёрная Пантера: Ваканда навеки",
                posterUrl:"https://kinopoiskapiunofficial.tech/images/posters/kp/1199773.jpg",
                posterUrlPreview:"https://kinopoiskapiunofficial.tech/images/posters/kp_small/1199773.jpg",
                rating:"6.7",
                ratingChange:null,
                ratingVoteCount:31829,
                year:"2022",
            },
            {
            countries:[
                {country: 'США'},
            ],
            filmId:4321512,
            filmLength:"01:57",
            genres:[
                {genre: 'драма'}
            ],
            nameEn:"The Whale",
            nameRu:"Кит",
            posterUrl:"https://kinopoiskapiunofficial.tech/images/posters/kp/4321512.jpg",
            posterUrlPreview:"https://kinopoiskapiunofficial.tech/images/posters/kp_small/4321512.jpg",
            rating:"99.0%",
            ratingChange:null,
            ratingVoteCount:560,
            year:"2022"
            },
            {
                countries:[
                    {country: 'США'}
                ],
                filmId:1392550,
                filmLength:"02:06",
                genres:[
                    {genre: 'боевик'},
                    {genre: 'комедия'},
                ],
                nameEn:"Bullet Train",
                nameRu:"Быстрее пули",
                posterUrl:"https://kinopoiskapiunofficial.tech/images/posters/kp/1392550.jpg",
                posterUrlPreview:"https://kinopoiskapiunofficial.tech/images/posters/kp_small/1392550.jpg",
                rating:"7.7",
                ratingChange:null,
                ratingVoteCount:95660,
                year:"2022",
            },

        ],
        genres: {
            countries: [
                {id: 1, country: 'США'},
                {id: 2, country: 'Швейцария'},
                {id: 3, country: 'Франция'},
                {id: 4, country: 'Польша'},
                {id: 5, country: 'Великобритания'},
                {id: 6, country: 'Швеция'},
                {id: 7, country: 'Индия'},
                {id: 8, country: 'Испания'},
                {id: 9, country: 'Германия'},
                {id: 10, country: 'Италия'},
                {id: 11, country: 'Гонконг'},
                {id: 12, country: 'Германия (ФРГ)'},
                {id: 13, country: 'Австралия'},
                {id: 14, country: 'Канада'},
                {id: 15, country: 'Мексика'},
                {id: 16, country: 'Япония'},
                {id: 17, country: 'Дания'},
                {id: 18, country: 'Чехия'},
                {id: 19, country: 'Ирландия'},
                {id: 20, country: 'Люксембург'},
                {id: 21, country: 'Китай'},
                {id: 22, country: 'Норвегия'},
                {id: 23, country: 'Нидерланды'},
                {id: 24, country: 'Аргентина'},
                {id: 25, country: 'Финляндия'},
                {id: 26, country: 'Босния и Герцеговина'},
                {id: 27, country: 'Австрия'},
                {id: 28, country: 'Тайвань'},
                {id: 29, country: 'Новая Зеландия'},
                {id: 30, country: 'Бразилия'},
                {id: 31, country: 'Чехословакия'},
                {id: 32, country: 'Мальта'},
                {id: 33, country: 'СССР'},
                {id: 34, country: 'Россия'},
                {id: 35, country: 'Югославия'},
                {id: 36, country: 'Португалия'},
                {id: 37, country: 'Румыния'},
                {id: 38, country: 'Хорватия'},
                {id: 39, country: 'ЮАР'},
                {id: 40, country: 'Куба'},
                {id: 41, country: 'Колумбия'},
                {id: 42, country: 'Израиль'},
                {id: 43, country: 'Намибия'},
                {id: 44, country: 'Турция'},
                {id: 45, country: 'Бельгия'},
                {id: 46, country: 'Сальвадор'},
                {id: 47, country: 'Исландия'},
                {id: 48, country: 'Венгрия'},
                {id: 49, country: 'Корея Южная'},
                {id: 50, country: 'Лихтенштейн'},
                {id: 51, country: 'Болгария'},
                {id: 52, country: 'Филиппины'},
                {id: 53, country: 'Доминикана'},
                {id: 54, country: ''},
                {id: 55, country: 'Марокко'},
                {id: 56, country: 'Таиланд'},
                {id: 57, country: 'Кения'},
                {id: 58, country: 'Пакистан'},
                {id: 59, country: 'Иран'},
                {id: 60, country: 'Панама'},
                ],
            genres : [
                {id: 1, genre: 'триллер'},
                {id: 2, genre: 'драма'},
                {id: 3, genre: 'криминал'},
                {id: 4, genre: 'мелодрама'},
                {id: 5, genre: 'детектив'},
                {id: 6, genre: 'фантастика'},
                {id: 7, genre: 'приключения'},
                {id: 8, genre: 'биография'},
                {id: 9, genre: 'фильм-нуар'},
                {id: 10, genre: 'вестерн'},
                {id: 11, genre: 'боевик'},
                {id: 12, genre: 'фэнтези'},
                {id: 13, genre: 'комедия'},
                {id: 14, genre: 'военный'},
                {id: 15, genre: 'история'},
                {id: 16, genre: 'музыка'},
                {id: 17, genre: 'ужасы'},
                {id: 18, genre: 'мультфильм'},
                {id: 19, genre: 'семейный'},
                {id: 20, genre: 'мюзикл'},
                {id: 21, genre: 'спорт'},
                {id: 22, genre: 'документальный'},
                {id: 23, genre: 'короткометражка'},
                {id: 24, genre: 'аниме'},
                {id: 25, genre: ''},
                {id: 26, genre: 'новости'},
                {id: 27, genre: 'концерт'},
                {id: 28, genre: 'для взрослых'},
                {id: 29, genre: 'церемония'},
                {id: 30, genre: 'реальное ТВ'},
                {id: 31, genre: 'игра'},
                {id: 32, genre: 'ток-шоу'},
                {id: 33, genre: 'детский'},
            ],
        },
        selectedCity: 600,
        filmData: {
            mainData: {
                completed: false,
                countries: [{country: 'Польша'}, {country: 'Япония'}],
                coverUrl: null,
                description: "В отдаленном будущем человечество осваивает виртуальный мир компьютерной игры под названием «Авалон». Лишь немногим удается достичь в игре финального уровня, а те, кто возвращаются, впадают в коматозное состояние. Чтобы попытаться спасти своего возлюбленного от этой участи, Эш преисполнена решимости пройти всю игру и встретиться в финале с загадочным персонажем по имени Призрак.",
                editorAnnotation: null,
                endYear: null,
                filmLength: 107,
                genres: [
                    {genre: 'драма'},
                    {genre: 'фантастика'},
                    {genre: 'боевик'}
                ],
                has3D: false,
                hasImax: false,
                imdbId: "tt0267287",
                isTicketsAvailable: false,
                kinopoiskId: 600,
                lastSync: "2022-12-31T03:49:13.549662",
                logoUrl: null,
                nameEn: null,
                nameOriginal: "Avalon",
                nameRu: "Авалон",
                posterUrl: "https://kinopoiskapiunofficial.tech/images/posters/kp/600.jpg",
                posterUrlPreview: "https://kinopoiskapiunofficial.tech/images/posters/kp_small/600.jpg",
                productionStatus: null,
                ratingAgeLimits: "age16",
                ratingAwait: null,
                ratingAwaitCount: 0,
                ratingFilmCritics: 6.9,
                ratingFilmCriticsVoteCount: 5,
                ratingGoodReview: 78.9,
                ratingGoodReviewVoteCount: 14,
                ratingImdb: 6.4,
                ratingImdbVoteCount: 13387,
                ratingKinopoisk: 6.2,
                ratingKinopoiskVoteCount: 3791,
                ratingMpaa: "r",
                ratingRfCritics: null,
                ratingRfCriticsVoteCount: 1,
                reviewsCount: 0,
                serial: false,
                shortDescription: null,
                shortFilm: false,
                slogan: "Настоящая матрица - это авалон",
                startYear: null,
                type: "FILM",
                webUrl: "https://www.kinopoisk.ru/film/600/",
                year: 2001,
            },
            stuff: [
                {nameRu: 'Мамору Осии', professionText: 'Режиссеры'},
                {nameRu: 'Малгожата Форемняк', professionText: 'Актеры'},
                {nameRu: 'Владислав Ковальский', professionText: 'Актеры'},
                {nameRu: 'Ежи Гудейко', professionText: 'Актеры'},
                {nameRu: 'Дариуш Бискупски', professionText: 'Актеры'},
                {nameRu: 'Бартломей Свидерский', professionText: 'Актеры'},
                {nameRu: 'Катажина Баргеловска', professionText: 'Актеры'},
                {nameRu: 'Алиция Сапрык', professionText: 'Актеры'},
                {nameRu: 'Михал Брейтенвальд', professionText: 'Актеры'},
                {nameRu: 'Зузанна Каш', professionText: 'Актеры'},
                {nameRu: 'Адам Шишковский', professionText: 'Актеры'},
                {nameRu: 'Кшиштоф Щербиньски', professionText: 'Актеры'},
                {nameRu: 'Марек Ставиньский', professionText: 'Актеры'},
                {nameRu: 'Ярослав Будник', professionText: 'Актеры'},
                {nameRu: 'Анджей Дембский', professionText: 'Актеры'},
                {nameRu: 'Эльжбета Товарницка', professionText: 'Актеры'},
                {nameRu: 'Здзислав Шимборски', professionText: 'Актеры'},
                {nameRu: 'Ацуси Кубо', professionText: 'Продюсеры'},
                {nameRu: 'Такэхико Тино', professionText: 'Продюсеры'},
                {nameRu: 'Рёити Фукуяма', professionText: 'Продюсеры'},
                {nameRu: 'Кадзуми Кавасиро', professionText: 'Продюсеры'},
                {nameRu: 'Тэцу Каяма', professionText: 'Продюсеры'},
                {nameRu: 'Синдзи Комори', professionText: 'Продюсеры'},
                {nameRu: 'Такэнари Маэда', professionText: 'Продюсеры'},
                {nameRu: 'Ясуки Мики', professionText: 'Продюсеры'},
                {nameRu: 'Кацухару Нагата', professionText: 'Продюсеры'},
                {nameRu: 'Кацухиро Огава', professionText: 'Продюсеры'},
                {nameRu: 'Наоюки Сакагами', professionText: 'Продюсеры'},
                {nameRu: 'Тору Сиобара', professionText: 'Продюсеры'},
                {nameRu: 'Нобуюки Тоя', professionText: 'Продюсеры'},
                {nameRu: 'Син Унодзава', professionText: 'Продюсеры'},
                {nameRu: 'Сигэру Ватанабэ', professionText: 'Продюсеры'},
                {nameRu: 'Кадзунори Ито', professionText: 'Сценаристы'},
                {nameRu: 'Гжегож Кендзерский', professionText: 'Операторы'},
                {nameRu: 'Кэндзи Каваи', professionText: 'Композиторы'},
                {nameRu: 'Барбара Новак', professionText: 'Художники'},
                {nameRu: 'Такаси Ватабэ', professionText: 'Художники'},
                {nameRu: 'Магдалена Бьернавска-Теславска', professionText: 'Художники'},
                {nameRu: 'Хироси Окуда', professionText: 'Монтажеры'}
            ],
            awards: [
                {name: 'Сан-Себастьян', win: true, imageUrl: null, nominationName: 'Приз Сан-Себастьяна за лучшую мужскую роль', year: 1975},
                {name: 'Оскар', win: true, imageUrl: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1600647/09035193-2458-4de7-a7df-ad8f85b73798/orig', nominationName: 'Лучший оригинальный сценарий', year: 1976},
                {name: 'Оскар', win: false, imageUrl: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1773646/931b548b-45a0-45ad-8127-148c423f850a/orig', nominationName: 'Лучший фильм', year: 1976},
                {name: 'Оскар', win: false, imageUrl: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1773646/931b548b-45a0-45ad-8127-148c423f850a/orig', nominationName: 'Лучшая мужская роль', year: 1976},
                {name: 'Оскар', win: false, imageUrl: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1773646/931b548b-45a0-45ad-8127-148c423f850a/orig', nominationName: 'Лучшая мужская роль второго плана', year: 1976},
                {name: 'Оскар', win: false, imageUrl: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1773646/931b548b-45a0-45ad-8127-148c423f850a/orig', nominationName: 'Лучший режиссер', year: 1976},
                {name: 'Оскар', win: false, imageUrl: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1773646/931b548b-45a0-45ad-8127-148c423f850a/orig', nominationName: 'Лучший монтаж', year: 1976},
                {name: 'Золотой глобус', win: false, imageUrl: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1777765/b3e8e35c-77b4-4331-a630-d4d9f264d314/orig', nominationName: 'Лучшая мужская роль (драма)', year: 1976},
                {name: 'Золотой глобус', win: false, imageUrl: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1777765/b3e8e35c-77b4-4331-a630-d4d9f264d314/orig', nominationName: 'Лучший фильм (драма)', year: 1976},
                {name: 'Золотой глобус', win: false, imageUrl: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1777765/b3e8e35c-77b4-4331-a630-d4d9f264d314/orig', nominationName: 'Лучшая мужская роль второго плана', year: 1976},
                {name: 'Золотой глобус', win: false, imageUrl: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1777765/b3e8e35c-77b4-4331-a630-d4d9f264d314/orig', nominationName: 'Лучший режиссер', year: 1976},
                {name: 'Золотой глобус', win: false, imageUrl: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1777765/b3e8e35c-77b4-4331-a630-d4d9f264d314/orig', nominationName: 'Лучший сценарий', year: 1976},
                {name: 'Золотой глобус', win: false, imageUrl: 'https://avatars.mds.yandex.net/get-kinopoisk-image/1777765/b3e8e35c-77b4-4331-a630-d4d9f264d314/orig', nominationName: 'Лучший дебютант', year: 1976},
                {name: 'Британская академия', win: true, imageUrl: null, nominationName: 'Лучшая мужская роль', year: 1976},
                {name: 'Британская академия', win: true, imageUrl: null, nominationName: 'Лучший монтаж', year: 1976},
                {name: 'Британская академия', win: false, imageUrl: null, nominationName: 'Лучший фильм', year: 1976},
                {name: 'Британская академия', win: false, imageUrl: null, nominationName: 'Лучший режиссер', year: 1976},
                {name: 'Британская академия', win: false, imageUrl: null, nominationName: 'Лучший сценарий', year: 1976},
                {name: 'Британская академия', win: false, imageUrl: null, nominationName: 'Лучший саундтрек', year: 1976},
            ],
            budget: [
                {type: 'BUDGET', amount: 8000000, currencyCode: 'USD', name: 'US Dollar', symbol: '$'},
                {type: 'WORLD', amount: 449275, currencyCode: 'USD', name: 'US Dollar', symbol: '$'}
            ]
        },
        personData:{},
        // selectedPerson: 13,
        filmography:[],
        filmographyId:[],
    },

    reducers: {
        fetchMovies(state, action) {
            state.movies = action.payload
        },
        fetchGenres(state, action) {
            state.genres = action.payload
        },
        fetchMovieData(state, action) {
            state.filmData = action.payload
        },
        fetchPersonData (state, action) {
            state.personData = action.payload
        },
        fetchFilmography (state, action) {
            state.filmography = action.payload
        },
        setSelectedPerson (state, action) {
            state.selectedPerson = action.payload
        },
        setFilmographyId (state, action) {
            state.filmographyId = action.payload
        },
        setSelectedMovie (state, action) {
            state.selectedMovie = action.payload
        },
        setSelectedGenre (state, action) {
            state.selectedGenre = action.payload
        },

    }

})

export const {
    fetchMovies,
    fetchGenres,
    fetchMovieData,
    fetchPersonData,
    fetchFilmography,
    setFilmographyId,
    setSelectedPerson,
    setSelectedGenre,
    setSelectedMovie,

} = MovieSlice.actions